export const DEFAULT_MIN_PRICE = 0;
export const DEFAULT_MAX_PRICE = 500000;
export const RATING_PAGE_LIMIT = 6;
export const DEFAULT_NOTIFICATION_PAGE = 1;
export const DEFAULT_NOTIFICATION_LIMIT = 6;
